image: "${GITLAB_DOCKER_PROXY}/maven:3.9-eclipse-temurin-25"

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Xmx4g -XX:+UseG1GC -XX:+TieredCompilation
    -XX:TieredStopAtLevel=1 -XX:CICompilerCount=2
  GITLAB_DOCKER_PROXY: "gitlab.education.tbank.ru:443/backend-academy-java-2025/lecture-materials/dependency_proxy/containers"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_PROTECTED == 'true'
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - build
  - lint
  - test

cache:
  key: "maven-cache-$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/

build:
  stage: build
  timeout: 20m
  script:
    - ./mvnw package -T 1C -DskipTests=true -Djacoco.skip=true
      -Denforcer.skip=true -Dflatten.skip=true
      -Dmodernizer.skip=true -Dspotbugs.skip=true -Dpmd.skip=true
      --projects '!build-report-aggregate' -am

lint:
  stage: lint
  needs: ["build"]
  cache:
    policy: pull
  script:
    - ./mvnw compile -T 1C -am spotless:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check

test:
  stage: test
  needs: ["build"]
  cache:
    policy: pull
  script:
    - ./mvnw clean package -DskipTests=true
    - ./mvnw verify -Dgroups='!integration'
