server:
  port: 8081

spring:
  data:
    redis:
      cluster:
        nodes: ${REDIS_CLUSTER_NODES:localhost:6379,localhost:6380,localhost:6381}
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 60s
  application:
    name: scrapper
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/${DB_NAME}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092,localhost:29092,localhost:39092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8081}
        auto.register.schemas: true

app:
  client:
    type: kafka
    timeout:
      connect-timeout: 3s
      read-timeout: 5s

  rate-limit:
    capacity: 20
    refill-period: 1m
    max-entries: 10000

  cache:
    l1-ttl: 1m
    l2-ttl: 10m
    l1-capacity: 1000
  db:
    access-type: orm
  pagination:
    default-page-size: 20
  threading:
    pool-size: 4

  kafka:
    topic: link.raw-updates
    outbox-checking-interval-ms: 60000
    outbox-checking-limit: 20
    max-retries-for-messages-outbox: 5
    days-interval-for-cleaning-outbox: 1
    outbox-cleaning-cron: "0 0 2 * * *"
  bot:
    url: ${APP_BOT_URL:http://localhost:8080}
  grpc:
    host: ${APP_GRPC_HOST:localhost}
    port: 9091

  stackoverflow:
    site: stackoverflow
    filter: "!*JK2R6f)iUdB8zQn9e6hYTcT)El5NN*4fKw)Y0vPLkly"
    batch-size: 100
    url: https://api.stackexchange.com/2.3
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}

resilience4j:
  retry:
    retry-aspect-order: 1
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: false
        exponential-backoff-multiplier: 2.0
        retryable-status-codes:
          - 500
          - 502
          - 503
          - 504
        retry-exceptions:
          - backend.academy.linktracker.scrapper.exception.RetryableApiException
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - java.io.UncheckedIOException
    instances:
      bot-notifier:
        base-config: default
      github-api:
        base-config: default
      stackoverflow-api:
        base-config: default
  circuitbreaker:
    circuit-breaker-aspect-order: 2
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 1s
    instances:
      bot-notifier:
        base-config: default
      github-api:
        base-config: default
      stackoverflow-api:
        base-config: default

notifications:
  divider: "────────────────"
  date-time-format: "yyyy-MM-dd HH:mm 'UTC'"
  labels:
    title: "Название: "
    question: "Вопрос: "
    author: "Автор: "
    time: "Время: "
    description: "Описание: "
    type-issue: "Issue"
    type-pr: "Pull Request"
    type-answer: "Ответ"
    type-comment: "Комментарий"
    empty-content: "—"
  error:
    title: "Не удалось обработать ссылку!"
  defaulting:
    title: "Обновление!"

errors:
  invalid-response: "Непредвиденная ошибка при обращении к внешнему сервису"

scheduler:
  interval-ms: 60000
