server:
  port: 8081

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/${DB_NAME}}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false

app:
  db:
    access-type: orm
  pagination:
    default-page-size: 20
  treading:
    executed-threads: 4
  client:
    type: http
  bot:
    url: ${APP_BOT_URL:http://localhost:8080}
  grpc:
    host: ${APP_GRPC_HOST:localhost}
    port: 9091

  stackoverflow:
    site: stackoverflow
    filter: "!*JK2R6f)iUdB8zQn9e6hYTcT)El5NN*4fKw)Y0vPLkly"
    batch-size: 100
    url: https://api.stackexchange.com/2.3
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}

notifications:
  divider: "────────────────"
  date-time-format: "yyyy-MM-dd HH:mm 'UTC'"
  labels:
    title: "Название: "
    question: "Вопрос: "
    author: "Автор: "
    time: "Время: "
    description: "Описание: "
    type-issue: "Issue"
    type-pr: "Pull Request"
    type-answer: "Ответ"
    type-comment: "Комментарий"
    empty-content: "—"
  limits:
    github-body: 200
    stackoverflow-answer: 200
    stackoverflow-comment: 200
  error:
    title: "Не удалось обработать ссылку!"
  defaulting:
    title: "Обновление!"

errors:
  invalid-response: "Непредвиденная ошибка при обращении к внешнему сервису"

scheduler:
  interval: 60000
