server:
  port: 8081

spring:
  application:
    name: scrapper
  grpc:
    server:
      port: 9090

app:
  client:
    type: grpc
  bot:
    url: "http://localhost:8080"
  grpc:
    host: localhost
    port: 9091

  stackoverflow:
    url: https://api.stackexchange.com/2.3
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}

notifications:
  default:
    title: "Обновление!"
    body: "%s"
errors:
  invalid-response: "Непредвиденная ошибка при обращении к внешнему сервису"

scheduler:
  interval: 60000

