server:
  port: 8080

spring:
  application:
    name: bot
  grpc:
    server:
      port: 9091
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092,localhost:29092,localhost:39092}
    consumer:
      group-id: ${app.kafka.group-id}
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        spring.json.value.default.type: backend.academy.linktracker.bot.dto.LinkUpdate
        spring.json.trusted.packages: "*"
        schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8085}
        specific.avro.reader: true


app:
  updates:
    type: kafka
  scrapper-client:
    type: grpc
  kafka:
    topic: link-updates
    group-id: bot-group
    dlt-topic: link-updates-dlt
    attempts: 3
    backoff-ms: 1000
  scrapper:
    url: ${APP_SCRAPPER_URL:http://localhost:8081}
  grpc:
    host: ${APP_GRPC_HOST:localhost}
    port: 9090
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false

bot:
  messages:
    welcome: "Добро пожаловать! Используйте /help, чтобы посмотреть доступные команды"
    help-header: "Доступные команды:"
    unknown-command: "Неизвестная команда. Воспользуйтесь /help, чтобы посмотреть список доступных команд"
    tracking: "Пришли ссылку для отслеживания. Если ты передумал пришли /cancel"
    untracking: "Пришли ссылку для прекращения отслеживания. Если ты передумал пришли /cancel"
    list: "Отслеживаемые ссылки:"
    canceling: "Действие отменено"

    tags-offer: "Хочешь добавить теги? (да/нет)"
    invalid-url: "Неверный формат ссылки (GitHub/StackOverflow)"
    tags-prompt: "Теги через запятую (/cancel для отмены)"
    invalid-tags-answer: "Ответь да/нет"
    links: "Ваши ссылки: "
    link-added: "Ссылка добавлена"
    link-added-with-tags: "Ссылка добавлена с тегами"
    link-deleted: "Ссылка удалена из отслеживания"
    link-not-found: "Ссылка не найдена в отслеживании"
    link-is-empty: "Ссылок не обнаружено"
    state-error: "Ошибка состояния. /track заново"
    invalid-response: "Ошибка при обращении к сервису Scrapper"
  commands:
    start:
      name: "/start"
      description: "Начать работу"
    help:
      name: "/help"
      description: "Вывести список доступных команд"
    track:
      name: "/track"
      description: "Начать отслеживание ссылки"
    untrack:
      name: "/untrack"
      description: "Прекратить отслеживание ссылки"
    list:
      name: "/list"
      description: "Вывести список отслеживаемых ссылок (опционально по тегу)"
    cancel:
      name: "/cancel"
      description: "Отменить действие"
  responses:
    needed-tags: "да"
    not-needed-tags: "нет"

sender:
  message-limit: 4096
  continuer: "Продолжение ниже..."
  delimiter: "─────────────────"
